apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: postgres-replicaset
spec:
  replicas: 3  # Specify the desired number of replicas
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        imagePullPolicy: Never
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        ports:
        - containerPort: 5432
          name: postgres
        resources:
          limits:
            cpu: "500m"
            memory: "128Mi"
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
      volumes:
      - name: db-data
        emptyDir: {}
